[profile.default]
libs = ['lib']
optimizer = true
optimizer_runs = 2000
out = 'out'
solc = "0.8.19"
src = 'src'

[fmt]
bracket_spacing = true
line_length = 100
tab_width = 4
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
